language: python
python:
#  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
#  - "3.2"
install:
  - pip install . --use-mirrors
  - pip install unittest2 --use-mirrors
script:
  - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/unit2 discover icalendar []
